import React from 'react'

export default function Home() {
  return (
    <main className="min-h-screen gradient-bg relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-yellow-500 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
        <div className="absolute top-40 left-40 w-80 h-80 bg-pink-500 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
      </div>

      {/* Floating Particles */}
      <div className="absolute inset-0">
        {[...Array(20)].map((_, i) => (
          <div
            key={i}
            className="particle"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
              animationDelay: `${Math.random() * 3}s`,
              animationDuration: `${2 + Math.random() * 3}s`
            }}
          />
        ))}
      </div>

      <div className="container mx-auto px-4 py-16 relative z-10">
        <div className="text-center">
          {/* Hero Section with Enhanced Design */}
          <div className="mb-16">
            <div className="inline-block p-4 glass rounded-full mb-8 animate-float">
              <div className="text-8xl">🚀</div>
            </div>
            <h1 className="text-7xl font-bold text-white mb-8 drop-shadow-2xl animate-float">
              Simple Test Website
            </h1>
            <p className="text-2xl text-blue-200 mb-12 max-w-3xl mx-auto">
              Built with AI Builder Orchestrator System!
            </p>

            {/* Hero Card with Glass Effect */}
            <div className="glass rounded-2xl shadow-2xl p-12 max-w-5xl mx-auto mb-16 animate-glow">
              <h2 className="text-4xl font-bold text-white mb-8">Welcome to Our Platform</h2>
              <p className="text-xl text-blue-100 mb-10 leading-relaxed">
                This is a test website generated by the AI Builder orchestrator system.
                It demonstrates the full pipeline from AI assistant to project generation.
              </p>
              <button className="btn-gradient text-white font-bold py-4 px-8 rounded-xl shadow-lg">
                ✨ Get Started
              </button>
            </div>
          </div>

          {/* Enhanced Features Section */}
          <div className="grid md:grid-cols-3 gap-8 mb-16">
            <div className="glass rounded-2xl shadow-2xl p-8 transform hover:scale-105 transition-all duration-300 animate-float">
              <div className="text-6xl mb-6 text-gradient-purple">🎨</div>
              <h3 className="text-2xl font-bold text-white mb-4">Modern Design</h3>
              <p className="text-blue-200 leading-relaxed">Beautiful, responsive design with Tailwind CSS and stunning visual effects</p>
            </div>
            <div className="glass rounded-2xl shadow-2xl p-8 transform hover:scale-105 transition-all duration-300 animate-float" style={{ animationDelay: '1s' }}>
              <div className="text-6xl mb-6 text-gradient-pink">⚡</div>
              <h3 className="text-2xl font-bold text-white mb-4">Fast Performance</h3>
              <p className="text-blue-200 leading-relaxed">Optimized with Next.js 14 for blazing fast speeds and smooth animations</p>
            </div>
            <div className="glass rounded-2xl shadow-2xl p-8 transform hover:scale-105 transition-all duration-300 animate-float" style={{ animationDelay: '2s' }}>
              <div className="text-6xl mb-6 text-gradient-blue">🤖</div>
              <h3 className="text-2xl font-bold text-white mb-4">AI Powered</h3>
              <p className="text-blue-200 leading-relaxed">Generated by advanced AI orchestrator system with intelligent design</p>
            </div>
          </div>

          {/* Enhanced Contact Form */}
          <div className="glass rounded-2xl shadow-2xl p-12 max-w-3xl mx-auto animate-glow">
            <h2 className="text-3xl font-bold text-white mb-8">Contact Us</h2>
            <form className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-blue-200 mb-3">Name</label>
                <input
                  type="text"
                  className="w-full px-4 py-3 input-glass rounded-xl focus:outline-none"
                  placeholder="Your name"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-blue-200 mb-3">Email</label>
                <input
                  type="email"
                  className="w-full px-4 py-3 input-glass rounded-xl focus:outline-none"
                  placeholder="your@email.com"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-blue-200 mb-3">Message</label>
                <textarea
                  rows={4}
                  className="w-full px-4 py-3 input-glass rounded-xl focus:outline-none resize-none"
                  placeholder="Your message..."
                ></textarea>
              </div>
              <button
                type="submit"
                className="w-full btn-gradient text-white font-bold py-4 px-8 rounded-xl shadow-lg"
              >
                📧 Send Message
              </button>
            </form>
          </div>

          {/* Enhanced Footer */}
          <div className="mt-16 text-center">
            <div className="glass rounded-xl p-6 inline-block animate-float">
              <p className="text-blue-200 text-lg">Built with ❤️ by AI Builder Orchestrator System</p>
              <p className="mt-3">
                <span className="inline-block gradient-bg-2 text-white px-4 py-2 rounded-full font-semibold shadow-lg">
                  ✅ Test Successful
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
